local f = io.open('KAZEM.lua', "rb")
local content = f:read("*all")
f:close()
os.execute('killall -9 KAZEM.sh')
os.execute('killall -9 tg')
os.execute('rm -rf KAZEM.lua')
os.execute('git reset --hard origin/master')
os.execute('git pull')
local fi = io.open('KAZEM.lua', "w+")
fi:write(tostring(content))
fi:close()
os.execute('chmod 777 tg && chmod 777 KAZEM.sh')
os.execute('screen ./KAZEM.sh')
